---
# tasks file for azwinsrv
- name: create Azure resource group
  azure_rm_resourcegroup:
      name: '{{azure_resource_group}}'
      location: eastus
      state: present

- name: create Azure virtual network in resource group
  azure_rm_virtualnetwork:
      name: '{{azure_virtual_network}}'
      resource_group: '{{azure_resource_group}}'
      address_prefixes_cidr:
      - 10.1.0.0/16
      state: present

- name: create Azure subnet in virtualnetwork
  azure_rm_subnet:
      name: '{{azure_subnet}}'
      state: present
      virtual_network_name: '{{azure_virtual_network}}'
      resource_group: '{{azure_resource_group}}'
      address_prefix_cidr: 10.1.0.0/24

- name: create Azure storage account
  azure_rm_storageaccount:
      name: '{{azure_storage_account}}'
      resource_group: '{{azure_resource_group}}'
      account_type: Standard_LRS

- name: Create a public ip address
  azure_rm_publicipaddress:
    resource_group: '{{azure_resource_group}}'
    name: '{{azure_public_ip_name}}'
    allocation_method: Static
    domain_name: '{{azure_virtual_machine}}'

- name: Create NIC
  azure_rm_networkinterface:
      resource_group: '{{azure_resource_group}}'
      name: '{{azure_public_nic_name}}'
      virtual_network: '{{azure_virtual_network}}'
      subnet: '{{azure_subnet}}'
      public_ip_name: '{{azure_public_ip_name}}'

- name: provision new Azure virtual host
  azure_rm_virtualmachine:
      admin_username: '{{azure_vm_username}}'
      admin_password: '{{azure_vm_password}}'
      os_type: Windows
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
      name: '{{azure_virtual_machine}}'
      resource_group: '{{azure_resource_group}}'
      state: present
      vm_size: Standard_D1
      storage_account_name: '{{azure_storage_account}}'
      network_interfaces: '{{azure_public_nic_name}}' 
      # virtual_network_name: '{{azure_virtual_network}}'
      # subnet_name: '{{azure_subnet}}'

- azure_rm_securitygroup:
      resource_group: '{{azure_resource_group}}'
      name: '{{azure_public_nic_name}}'
      rules:
          - name: 'AllowRDPPorts'
            protocol: Tcp
            destination_port_range: 3389 
            access: Allow
            direction: Inbound
            priority: 102
          - name: 'AllowWinRMPorts'
            protocol: Tcp
            destination_port_range: 5986 
            access: Allow
            direction: Inbound
            priority: 103
          - name: 'AllowSQLPorts'
            protocol: Tcp
            destination_port_range: 1433 
            access: Allow
            direction: Inbound
            priority: 104

- name: create Azure vm extension to enable HTTPS WinRM listener
  azure_rm_virtualmachine_extension:
      name: winrm-extension
      resource_group: '{{azure_resource_group}}'
      virtual_machine_name: '{{azure_virtual_machine}}'
      publisher: Microsoft.Compute
      virtual_machine_extension_type: CustomScriptExtension
      type_handler_version: 1.9
      settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
      auto_upgrade_minor_version: true

- name: wait for the WinRM port to come online
  wait_for:
      port: 5986
      host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
      timeout: 600